### ISSUE TITLE
Font substitution problem on Ubuntu

### ISSUE THREAD

**Issue by dvbuntu** [c-bec-k/GenesysRPG#1]
Great package.  I wanted to extend your character sheet example at https://drive.google.com/file/d/1uOZHOzPa_Q8_lT6o8at9CA9v-sWe2EEo/view?usp=sharing, but I'm running into issues with fonts.  I was able to get XeLaTeX to find the fonts you provided, but it has trouble finding appropriate bold and small caps versions.  I get a warning such as:

```
LaTeX Font Warning: Font shape `OMS/Crimson(0)/m/n' undefined
(Font)              using `OMS/cmsy/m/n' instead
(Font)              for symbol `textbullet' on input line 183.
```

Things still compile, but all the appropriate fonts have been replaced with standard LaTeX Computer Modern.  Pretty for technical documents but it doesn't fit with the theme.

I suspect this might be because I'm using XeLaTeX (required for `fontspec`) on Ubuntu, and you might be using a different operating system.  I wonder if there are standard TexLive fonts (even in extended packages) that might be easier to use even if they don't match perfectly.

**Comment by dvbuntu** [comment]
Seems the `fontenc` package was the culprit.  Commenting out line 22 of `genesys.sty` essentially fixed my problem.

**Comment by c-bec-k** [comment]
I went ahead and commented out line 22 in the repo. Thanks for bringing this to my attention!
